### ISSUE TITLE
How to build reflex-todomvc and use it as a template?

### ISSUE THREAD

**Issue by BernardNotarianni** [ryantrinkle/reflex-todomvc#7]
I am newbie to reflex (and nix/nixos). I would like to use this reflex-todomvc app as a template to start modifiying, refactoring and learn by doing.

How could I build it as a standalone app in the local directory?

```
$ git clone https://github.com/ryantrinkle/reflex-todomvc.git
$ cd reflex-todomvc
$ ??? 
```

Thanx for your help.

**Comment by paldepind** [comment]
I am curious about this as well. I'd like to build the application from inside the try-reflex environment?

**Comment by jbgi** [comment]
To build the demo with stack instead of nix: https://github.com/jbgi/reflex-todomvc/tree/ghcjs-improved-base
(slightly adapted from: https://github.com/luigy/try-stack-reflex)

**Comment by 3noch** [comment]
You can install the latest GHCJS for use with stack using [this turtle script](https://gist.github.com/3noch/4696feff5c602e126681). With slight modification, you could have it install older an older version as well. Essentially it formats the sdist archive differently and places it in the right place so that stack will know how to boot it.

**Comment by jbgi** [comment]
@3noch really handy! thanks!
